### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by jpbalbu** [indie-pocket/indie-pocket#20]
comments for 0.6.4-s4 version

- [x] 1. "recording (time)" counter was better to understand it's currently recording or not (comment from Audrey)
- [x] 2. can we deactivate the screen rotation? it doesn't make sense
- [x] 3. come back to "NOT RECODING" or "PAUSE" + grey "flash light" when click pause
- [x] 4. had sometimes this kind of display issue. Then click "action" back to "placement" and the app crashed
- [x] 5. maybe now with big icons we can write "Pants front pocket" "Pants back pocket" "Jacket front pocket"

some issue with "less clicks" mode:
- [x] 6. when stopped, impossible to "continue recording" (goes back to locked screen). It should go back to the beginning or remove the "continue recording" with less clicks mode
- [x] 7. impossible to unzip during countdown if we made a mistake. is it voluntary?
- [x] 8. remove back navigation

![Screenshot_20200422-181811_indiepocket](https://user-images.githubusercontent.com/63728269/80007613-c57e4800-84c6-11ea-9dd9-bc6b4b7683a4.jpg)

**Comment by ineiti** [comment]
1, 2, 3, 5 - OK, will do

4 - hmm, that's funny. The 'Placement tab' only shows when the `tab` variable is 0. The 'Action tab' only shows when the `tab` variable is 1. So I have no idea how nativescript managed to have the `tab` variable be both 0 and 1. I'm sure I didn't add the `qubit` compiler flag!

6 - proposal: for `lessClick`, change `Continue Recording` to `Change Placement` and go back to the choose-screen when clicked
7 - that's on purpose. The idea is that the user has 5 seconds to put the phone in her pocket. But I can change it so that unzipping during these 5 seconds puts the phone back to the choose screen

8 - I'll have to remove the `back` navigation - I think it screws things up too much.
